# eksctl 설정 파일 버전 정의
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

# 클러스터 기본 정보 설정
metadata:
  name: jiwon-cluster-1 # 생성할 EKS 클러스터 이름 (태그와 일치해야 함)
  region: ap-southeast-1 # 클러스터가 생성될 리전 (도쿄)
  version: "1.31" # 쿠버네티스 제어 평면 버전(1.29 ~ 1.35 지원, 1.31 권장)

# 기존 VPC 및 서브넷 활용 설정
vpc:
  id: "vpc-065736a1357fa2ef3" # 사용자가 UI로 생성한 기존 VPC ID
  subnets:
    # 외부 로드밸런서가 위치할 퍼블릭 서브넷 (elb 태그 필요)
    public:
      ap-southeast-1a: { id: "subnet-076dc7032aeb4e9c2" }
      ap-southeast-1b: { id: "subnet-03716b1f01e3fb66d" }
      ap-southeast-1c: { id: "subnet-0470871a1ed34a479" }
    # 실제 워커 노드가 위치할 프라이빗 서브넷 (internal-elb 태그 필요)
    private:
      ap-southeast-1a: { id: "subnet-09396c186ccc6c5ab" }
      ap-southeast-1b: { id: "subnet-0ff170cfc355587f9" }
      ap-southeast-1c: { id: "subnet-04083f6631c6f591f" }
  clusterEndpoints:
    publicAccess: true # 보안 관점에선 false 권장, 하지만 CI/CD 환경에선 true 필요(외부 접속 허용)
    privateAccess: true

# 관리형 노드 그룹(Managed Node Group) 설정
managedNodeGroups:
  - name: jiwon-cluster-ng-1 # 노드 그룹의 이름
    instanceType: t3.medium # 사용할 EC2 인스턴스 타입 (사양)
    minSize: 1                 # 최소 1대 유지
    maxSize: 3                 # 최대 3대까지 확장 가능
    desiredCapacity: 2         # 초기 생성할 노드 개수
    volumeSize: 20 # 각 노드의 EBS(디스크) 크기 (GB)
    privateNetworking: true # 노드들을 외부 인터넷에 노출되지 않는 프라이빗 서브넷에 배치
    securityGroups:
      attachIDs:
        - sg-0ea1b7f0a7f575b72 # 이미 만들어두신 보안 그룹 ID
    iam:
      # 노드에 기본적으로 필요한 AWS 정책 권한 추가
      withAddonPolicies:
        imageBuilder: true # ECR 이미지 접근 권한
        autoScaler: true # Cluster Autoscaler 사용을 위한 권한
        albIngress: true # 로드밸런서 관련 기본 권한을 노드에 자동으로 부여
        cloudWatch: true # 로그 전송을 위한 CloudWatch 권한
        ebs: true # EBS 볼륨 사용 권한
        certManager: true # SSL/TLS 인증서 자동 발급 권한
        externalDNS: true # 도메인 (Route53) 자동 연결 권한 

# IAM OIDC 프로바이더 설정
iam:
  withOIDC: true # 쿠버네티스 서비스 계정에 IAM 역할을 부여하기 위한 설정 (필수) (AWS내의 다른 서비스와 연결될 수 있는 권한)


